name: My First Github Action
on: [push]
jobs:
    print_hello_world:
        runs-on: ubuntu-latest
        steps:
            - run: echo "hello world!!!"
            - run: echo "this is step number 2"
    print_hello_world2:
        runs-on: ubuntu-latest
        steps:
            - run: echo "hello world!!!"
            - run: echo "this is step number 2"            